name: generator
environment: { sdk: ^3.4.3 }
executables: { pb_generator: generator }
dev_dependencies: { lints: ^3.0.0 }
dependencies:
  args: ^2.5.0
  built_collection: ^5.1.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  mason_logger: ^0.2.15
  pocketbase: ^0.18.1
  recase: ^4.1.0
