include: package:very_good_analysis/analysis_options.yaml

formatter: { page_width: 100, trailing_commas: preserve }

linter:
  rules:
    public_member_api_docs: false

analyzer:
  exclude: ["**.g.dart", "**.mapper.dart"]
  plugins: [custom_lint]

  errors:
    lines_longer_than_80_chars: ignore
