include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false

analyzer:
  errors:
    omit_local_variable_types: ignore
    prefer_const_constructors: ignore
    prefer_const_constructors_in_immutables: ignore
