name: app
publish_to: "none"
version: 0.0.1
environment: { sdk: ">=3.3.0 <4.0.0" }
flutter: { uses-material-design: true }

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  flutter: { sdk: flutter }
  flutter_bloc: ^8.1.4
  http: ^1.2.1
  theme_extensions_builder_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test: { sdk: flutter }
  theme_extensions_builder: ^3.1.0
  very_good_analysis: ^5.1.0
