name: app
publish_to: "none"
version: 0.0.1
environment: { sdk: ">=3.3.0 <4.0.0" }

dependencies:
  cupertino_icons: ^1.0.6
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
executables:
  - example
