name: app
publish_to: "none"
version: 0.0.1
environment: { sdk: ">=3.3.0 <4.0.0" }
flutter: 
  uses-material-design: true
  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/Open_Sans/static/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open_Sans/static/OpenSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Open_Sans/static/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/Open_Sans/static/OpenSans-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/Open_Sans/static/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/Open_Sans/static/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Open_Sans/static/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Open_Sans/static/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/Open_Sans/static/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open_Sans/static/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Open_Sans/static/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/Open_Sans/static/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic


dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  dart_mappable: ^4.2.1
  flex_color_scheme: ^7.3.1
  flutter: { sdk: flutter }
  flutter_bloc: ^8.1.4
  http: ^1.2.1
  pocketbase: ^0.18.1
  shared_preferences: ^2.2.2
  stream_transform: ^2.1.0
  theme_extensions_builder_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.8
  dart_mappable_builder: ^4.2.1
  flutter_test: { sdk: flutter }
  theme_extensions_builder: ^3.1.0
  very_good_analysis: ^5.1.0
