name: app
publish_to: "none"
version: 0.0.1
environment: { sdk: ">=3.3.0 <4.0.0" }

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  flutter: { sdk: flutter }
  flutter_bloc: ^8.1.4
  flutter_riverpod: ^2.5.1
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_test: { sdk: flutter }
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
