name: fundwise_server
version: 0.0.1
publish_to: none
environment: { sdk: ">=3.3.0 <4.0.0" }

dependencies:
  collection: ^1.18.0
  dart_frog: ^1.0.0
  faker: ^2.1.0
  fundwise_database: { path: ../database }

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
