name: flailwind
description: Tailwind-like styling in Flutter with text styles and colors.
version: 0.0.1
homepage: https://github.com/Luckey-Elijah/fundwise/tree/main/flailwind

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies: { flutter: { sdk: flutter } }

dev_dependencies:
  flutter_test: { sdk: flutter }
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
